import json
import os

def create_eda_notebook():
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Exploratory Data Analysis (EDA)\n",
                    "## Forecasting Financial Inclusion in Ethiopia\n",
                    "\n",
                    "This notebook performs exploratory data analysis on the unified financial inclusion dataset for Ethiopia. It covers:\n",
                    "1. **Dataset Overview**: Summaries by record type, pillar, source type, and confidence levels.\n",
                    "2. **Access Analysis**: Account ownership trajectory, growth rates, and gender gap analysis.\n",
                    "3. **Usage Analysis**: Mobile money and digital payment adoption trends.\n",
                    "4. **Infrastructure and Enablers**: 4G coverage, mobile subscription, and Fayda Digital ID registration.\n",
                    "5. **Event Timeline**: Visual overlay of key product and policy milestones on trend lines.\n",
                    "6. **Correlation Analysis**: Direct association between enablers and inclusion targets.\n",
                    "7. **Data Quality Assessment**: Limitations and sparse data coverage."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import pandas as pd\n",
                    "import numpy as np\n",
                    "import matplotlib.pyplot as plt\n",
                    "import seaborn as sns\n",
                    "import os\n",
                    "from IPython.display import Image, display\n",
                    "\n",
                    "# Set plots to display inline\n",
                    "%matplotlib inline\n",
                    "\n",
                    "# Paths\n",
                    "DATA_PATH = '../data/processed/ethiopia_fi_unified_data.csv'\n",
                    "IMPACT_PATH = '../data/processed/ethiopia_fi_impact_links.csv'\n",
                    "FIG_PATH = '../reports/figures/'"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 1. Dataset Overview\n",
                    "Let's load the data and review the counts of observations, events, targets, and pillars."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "df_data = pd.read_csv(DATA_PATH)\n",
                    "df_impact = pd.read_csv(IMPACT_PATH)\n",
                    "\n",
                    "print(\"=== Record Counts by Type ===\")\n",
                    "print(df_data['record_type'].value_counts())\n",
                    "print(\"\\n=== Record Counts by Pillar ===\")\n",
                    "print(df_data['pillar'].value_counts(dropna=False))\n",
                    "print(\"\\n=== Confidence Distribution ===\")\n",
                    "print(df_data['confidence'].value_counts())"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Temporal Data Coverage\n",
                    "Below is the temporal coverage of our key indicators from 2011 to 2025. Blue cells indicate years with actual observations."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Display temporal coverage plot generated by the script\n",
                    "display(Image(filename=os.path.join(FIG_PATH, 'temporal_coverage.png')))"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 2. Access Analysis: Account Ownership Trajectory (2011-2024)\n",
                    "We plot the account ownership rate (`ACC_OWNERSHIP`) trajectory over time, including gender-disaggregated trends."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "display(Image(filename=os.path.join(FIG_PATH, 'account_ownership_trajectory.png')))"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### Account Ownership Growth Rates\n",
                    "Let's print the actual numbers and calculate growth rates between survey years."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "df_obs = df_data[df_data['record_type'] == 'observation'].copy()\n",
                    "df_obs['year'] = pd.to_datetime(df_obs['observation_date']).dt.year\n",
                    "\n",
                    "df_acc_nat = df_obs[(df_obs['indicator_code'] == 'ACC_OWNERSHIP') & (df_obs['gender'] == 'all')].sort_values('year')\n",
                    "df_acc_nat['growth_pp'] = df_acc_nat['value_numeric'].diff()\n",
                    "df_acc_nat['growth_pct'] = df_acc_nat['value_numeric'].pct_change() * 100\n",
                    "print(df_acc_nat[['year', 'value_numeric', 'growth_pp', 'growth_pct']].to_string(index=False))"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 3. Usage (Digital Payments) vs Mobile Money Accounts\n",
                    "We analyze the relationship between Account Access, Mobile Money Accounts, and Digital Payment adoption rates. This highlights the gap between *registration* and *usage*."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "display(Image(filename=os.path.join(FIG_PATH, 'digital_payments_vs_mobile_money.png')))"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 4. Infrastructure and Enablers\n",
                    "We inspect the growth of 4G coverage, mobile subscription penetration, and the Fayda national biometric digital ID registrations."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "display(Image(filename=os.path.join(FIG_PATH, 'infrastructure_enablers.png')))"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 5. Event Timeline Overlay\n",
                    "We overlay regulatory changes (e.g. mobile money directive ONPS/01/2020), product launches (e.g. Telebirr, M-Pesa), and ecosystem milestones on our inclusion metrics."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "display(Image(filename=os.path.join(FIG_PATH, 'event_timeline_overlay.png')))"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 6. Correlation Analysis\n",
                    "Using linear interpolation to align the sparse data points across years (2011-2025), we inspect how enablers associate with our inclusion indicators."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "display(Image(filename=os.path.join(FIG_PATH, 'correlation_matrix.png')))"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 7. Key Insights & Data Quality Assessment\n",
                    "\n",
                    "### 5 Key Insights:\n",
                    "1. **Decelerating Access Growth (2021-2024)**: Despite the massive expansion of mobile money (Telebirr launching in 2021), account ownership growth slowed from +11pp (2017-2021) to just +3pp (2021-2024). This indicates that the initial mobile money push onboarded users who already had bank accounts, rather than reaching the unbanked.\n",
                    "2. **Persistent Gender Gap**: Women hold only 14% of mobile money accounts and exhibit a persistent 15pp gap in account ownership (56.5% male vs 41.6% female in 2024). This represents a major barrier to universal inclusion.\n",
                    "3. **P2P Crossover Dominance**: P2P transfers have surpassed ATM cash withdrawals for the first time in FY2024/25, with a crossover ratio of 1.08. Digital transaction volume growth (+158% YoY) far outpaces cash (+26%), signifying a structural shift from cash to digital.\n",
                    "4. **Usage vs. Ownership Gap**: Although over 65 million mobile money accounts are registered, the 2024 survey indicates digital payment usage (Usage) stands at ~35% and active mobile money rate is ~9.45% (mostly bank-linked). Active usage is constrained by digital literacy and network coverage.\n",
                    "5. **High Correlation with Mobile Money**: Account Ownership has a strong correlation (0.94) with Digital Payment usage, indicating that digital payment adoption cannot occur without primary account access. However, enablers like 4G coverage (0.89 correlation with P2P volume) are strong drivers of transaction frequency.\n",
                    "\n",
                    "### Data Quality Limitations:\n",
                    "- **Sparse Time Series**: The core indicators are survey-based and only updated every 3-4 years (5 data points over 15 years), limiting traditional time-series methods.\n",
                    "- **Missing Gender/Rural-Urban Disaggregation**: Many intermediate years lack demographic disaggregation.\n",
                    "- **Short Infrastructure Trajectory**: Infrastructure data (like Fayda or 4G coverage) only covers recent years (2023-2025), which limits historical correlation validation."
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }
    
    notebook_path = 'notebooks/02_exploratory_data_analysis.ipynb'
    with open(notebook_path, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=2)
    print(f"Created {notebook_path}")

if __name__ == '__main__':
    create_eda_notebook()
